devices:
  - alioth
  - cas
  - cmi
  - courbet
  - haydn
  - ingres
  - lisa
  - munch
  - odin
  - psyche
  - redwood
  - renoir
  - sapphiren
  - sky
  - topaz
  - vayu
  - venus
  - zeus
  - aristotle
